### ISSUE TITLE
OpenCV error after installing PeekingDuck 1.3.0 due to OpenCV version

### ISSUE THREAD

**Issue by leeping-ng** [aisingapore/PeekingDuck#693]
I'm using an Intel MacBook Pro (2017) on Big Sur, and ran into this issue right after upgrading my PeekingDuck to 1.3.0:
```
Successfully installed opencv-contrib-python-4.6.0.66 peekingduck-1.3.0 torch-1.10.0 torchvision-0.11.1 typeguard-2.13.3 typing-extensions-4.3.0
(pkd) Ngs-MacBook-Pro:Repositories ngleeping$ peekingduck verify-install
2022-08-18 17:37:18 root  ERROR:  Traceback (most recent call last):
   File "/opt/anaconda3/bin/peekingduck", line 5, in <module>
    from peekingduck.cli import cli
   File "/opt/anaconda3/lib/python3.7/site-packages/peekingduck/cli.py", line 22, in <module>
    from peekingduck.commands.core import init, run, verify_install
   File "/opt/anaconda3/lib/python3.7/site-packages/peekingduck/commands/core.py", line 31, in <module>
    from peekingduck.viewer import Viewer
   File "/opt/anaconda3/lib/python3.7/site-packages/peekingduck/viewer/__init__.py", line 19, in <module>
    from peekingduck.viewer.viewer import Viewer
   File "/opt/anaconda3/lib/python3.7/site-packages/peekingduck/viewer/viewer.py", line 32, in <module>
    import cv2
   File "/opt/anaconda3/lib/python3.7/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
   File "/opt/anaconda3/lib/python3.7/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
   File "/opt/anaconda3/lib/python3.7/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
   File "/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
   File "/opt/anaconda3/lib/python3.7/site-packages/cv2/mat_wrapper/__init__.py", line 33, in <module>
    cv._registerMatType(Mat)
 
2022-08-18 17:37:18 root  ERROR:  AttributeError: module 'cv2' has no attribute '_registerMatType'
```

Note that OpenCV version 4.6.0.66 was installed with PeekingDuck - I downgraded my OpenCV version to 4.5.2.54 and the problem was resolved. We may need to include an upper bound for OpenCV versions - to be determined with further tests.

**Comment by leeping-ng** [comment]
On the same environment described above, I upgraded OpenCV to 4.6.0.66 and didn't experience the above issue when I tried to run peekingduck again. I went on to create fresh conda environments for Python 3.6, 3.7, 3.8, and 3.9, and could not replicate this issue. Looks like it was due to a package conflict with my old environment - am going to close this issue.
